// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
// import { Plus_Jakarta_Sans, JetBrains_Mono } from "next/font/google";
// import "./globals.css";

// const jakarta = Plus_Jakarta_Sans({
//   subsets: ["latin"],
//   variable: "--font-jakarta",
//   display: "swap",
// });

// const jetbrains = JetBrains_Mono({
//   subsets: ["latin"],
//   variable: "--font-jetbrains",
//   display: "swap",
// });

// export const metadata = {
//   title: "Dhurandhar",
//   description: "Hands-on VPS & DevOps Learning Platform",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${jakarta.variable} ${jetbrains.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }

import "./globals.css";

import {
  Plus_Jakarta_Sans,
  JetBrains_Mono,
} from "next/font/google";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta",
  display: "swap",
});

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
  display: "swap",
});

export const metadata = {
  title: "Dhurandhar",
  description: "Hands-on VPS & DevOps Learning Platform",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jakarta.variable} ${jetbrains.variable}`}
      >
        {children}
      </body>
    </html>
  );
}